#!/bin/bash
#Usage: buildMainCpp.sh <lib_directory>


set -euo pipefail

LIB_DIR="$1"

cd "$LIB_DIR"

echo "/**
 * This file was auto-generated by buildMainCpp.sh from
 * https://github.com/abadiet/CWraPPer/.
 * It includes all headers from $LIB_DIR.
 */" > "main.cpp"

find . -type f \( -name "*.h" -o -name "*.hpp" \) | sort | while read -r header; do
    echo "#include \"$header\"" >> "main.cpp"
done

echo "" >> "main.cpp"
echo "int main() { return 0; }" >> "main.cpp"

echo "$LIB_DIR/main.cpp generated with all headers from $LIB_DIR."
